<?php

namespace Elly\WorkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * practicasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class practicasRepository extends EntityRepository
{
}
